"""Stating a change as a patch instead of as the span it replaces.

`edit` identifies what to change by quoting the whole of it. That has one
failure this codebase has now paid for: **the far end of the quote can be in
the wrong place, and the edit still applies.** Measured — an attempt replaced
the head of a multi-line RSpec matcher with a well-formed replacement and left
the tail of the regex literal behind, welded onto the new code. The result was
a syntax error, the tool reported "applied 1 edit(s)", and the model spent 96
further calls trying to repair a file it could not see.

A V4A hunk cannot express that mistake. Every removed line is named, so the
tail is either listed for removal or it survives visibly as context; there is
no way to say "from here to somewhere" and be wrong about the somewhere. That
property — not tolerance — is why this tool exists beside `edit`.

Which is also why it is applied **exactly**. A context diff's ordinary failure
mode is a hunk landing somewhere plausible and wrong, which commits, tests and
sometimes passes; a refusal costs one tool call. The format is the borrowed
part. The matching policy is ours, and it is strict.

The shape follows the installed OpenAI SDK's `apply_patch` operations
(`create_file` / `update_file` / `delete_file`, with `path` beside a `diff`) so
a model trained on that surface emits what it already knows — but it is
declared as an ordinary function tool, because the hosted type exists only on
the Responses wire and this executor's model is a routing policy whose wire is
not knowable until it resolves.
"""

import subprocess

import pytest

from code_gantry.edittools import (
    Edit,
    FileEditor,
    ToolError,
    apply_v4a,
    changed_windows,
    parse_v4a,
)

# The bytes that broke, near enough. A Ruby extended-mode regex literal inside
# a matcher: the file's own content is full of backslash escapes, which is what
# made every quote of it look like a pattern and none of them one.
SPEC = """\
    it 'returns false when the gateway raises' do
      expect(Rails.logger).to have_received(:warn).with(
        a_string_matching(
          /
            \\A\\[authorize-net\\sfailure\\]\\screate_customer_profile\\s
            user_id=123\\s
            StandardError:\\sgateway\\sfailure\\s\\(raised\\sat\\s.+\\)\\z
          /x,
        ),
      ).once
    end
"""

HEAD = """\
      expect(Rails.logger).to have_received(:warn).with(
        a_string_matching(
          /
            \\A\\[authorize-net\\sfailure\\]\\screate_customer_profile\\s
            user_id=123\\s
"""

AIRBRAKE = """\
      expect(Airbrake).to have_received(:notify).with(
        error,
        hash_including(parameters: hash_including(user_id: user.id.to_s)),
      ).once
"""


@pytest.fixture
def editor(tmp_path):
    repo = tmp_path / "t"
    (repo / "spec").mkdir(parents=True)
    (repo / "spec" / "a_spec.rb").write_text(SPEC)
    (repo / "bin").mkdir()
    (repo / "bin" / "gen.rb").write_text("# generated\n")
    for args in (
        ["git", "init", "-q"],
        ["git", "config", "user.email", "t@example.com"],
        ["git", "config", "user.name", "T"],
        ["git", "config", "commit.gpgsign", "false"],
        ["git", "add", "-A"],
        ["git", "commit", "-q", "-m", "first"],
    ):
        subprocess.run(args, cwd=repo, check=True)
    return FileEditor(
        repo=repo,
        edit_files=["spec/**", "bin/**"],
        no_direct_edit=[("bin/gen.rb", "it is generated by the generator")],
    )


def read(editor, rel="spec/a_spec.rb"):
    return (editor.repo / rel).read_text()


class TestTheCorruptionThisPrevents:
    def test_an_edit_can_replace_a_head_and_strand_the_tail(self, editor):
        # Not a defect in `edit` — this is what an exact, unique, correctly
        # applied replacement looks like when the quote stops in the wrong
        # place. It is here so the next reader can see that the two tools fail
        # differently rather than that one of them is broken.
        editor.edit("spec/a_spec.rb", [Edit(old_string=HEAD, new_string=AIRBRAKE)])
        after = read(editor)

        # Regex source stranded directly after a line of Ruby: the head went,
        # the tail stayed, and the tool reported success.
        assert ").once\n            StandardError:" in after
        assert "/x," in after

    def test_the_same_change_as_a_patch_removes_the_whole_construct(self, editor):
        diff = (
            "-      expect(Rails.logger).to have_received(:warn).with(\n"
            "-        a_string_matching(\n"
            "-          /\n"
            "-            \\A\\[authorize-net\\sfailure\\]\\screate_customer_profile\\s\n"
            "-            user_id=123\\s\n"
            "-            StandardError:\\sgateway\\sfailure\\s\\(raised\\sat\\s.+\\)\\z\n"
            "-          /x,\n"
            "-        ),\n"
            "-      ).once\n"
            "+      expect(Airbrake).to have_received(:notify).with(\n"
            "+        error,\n"
            "+      ).once\n"
        )
        editor.apply_patch("spec/a_spec.rb", "update_file", diff)
        after = read(editor)

        assert "Rails.logger" not in after
        assert "\\sgateway\\sfailure" not in after
        assert "/x," not in after
        assert "expect(Airbrake)" in after

    def test_a_patch_that_forgets_the_tail_is_refused_rather_than_applied(
        self, editor
    ):
        # The same mistake, expressed in the other format. `edit` cannot see
        # it; here the surviving lines are context that has to match, and they
        # do not sit where the hunk says they do.
        diff = (
            "-      expect(Rails.logger).to have_received(:warn).with(\n"
            "-        a_string_matching(\n"
            "-          /\n"
            "-            \\A\\[authorize-net\\sfailure\\]\\screate_customer_profile\\s\n"
            "-            user_id=123\\s\n"
            "+      expect(Airbrake).to have_received(:notify).with(\n"
            "+        error,\n"
            "+      ).once\n"
            "       end\n"
        )
        with pytest.raises(ToolError) as e:
            editor.apply_patch("spec/a_spec.rb", "update_file", diff)

        assert "do not appear in the file" in str(e.value)
        assert read(editor) == SPEC


class TestStrictMatching:
    def test_one_wrong_space_is_refused_rather_than_fuzzed(self, editor):
        diff = "-       user_id=123\\s\n+       user_id=456\\s\n"
        with pytest.raises(ToolError) as e:
            editor.apply_patch("spec/a_spec.rb", "update_file", diff)
        assert e.value.kind == "patch not found"
        assert read(editor) == SPEC

    def test_a_hunk_matching_twice_is_refused(self, tmp_path):
        ed = _repo_with(tmp_path, "app/a.rb", "def x\n  save\nend\ndef y\n  save\nend\n")
        with pytest.raises(ToolError) as e:
            ed.apply_patch("app/a.rb", "update_file", "-  save\n+  save!\n")
        assert e.value.kind == "patch ambiguous"
        assert "2 places" in str(e.value)

    def test_a_scope_header_picks_one_of_two_identical_blocks(self, tmp_path):
        ed = _repo_with(tmp_path, "app/a.rb", "def x\n  save\nend\ndef y\n  save\nend\n")
        ed.apply_patch("app/a.rb", "update_file", "@@ def y\n-  save\n+  save!\n")
        assert (ed.repo / "app/a.rb").read_text() == (
            "def x\n  save\nend\ndef y\n  save!\nend\n"
        )

    def test_a_scope_header_naming_nothing_says_so(self, tmp_path):
        ed = _repo_with(tmp_path, "app/a.rb", "def x\n  save\nend\n")
        with pytest.raises(ToolError) as e:
            ed.apply_patch("app/a.rb", "update_file", "@@ def nope\n-  save\n+  save!\n")
        assert "names a place that is not there" in str(e.value)

    def test_a_failing_hunk_rolls_back_the_ones_before_it(self, tmp_path):
        ed = _repo_with(tmp_path, "app/a.rb", "one\ntwo\nthree\n")
        with pytest.raises(ToolError):
            ed.apply_patch(
                "app/a.rb",
                "update_file",
                "-one\n+ONE\n@@\n-nonexistent\n+X\n",
            )
        assert (ed.repo / "app/a.rb").read_text() == "one\ntwo\nthree\n"


class TestTheFormat:
    def test_an_empty_line_is_context(self):
        # Models emit a bare line for a blank context line, because trailing
        # whitespace is invisible and editors strip it. Refusing those would
        # make the format unusable on any file containing a blank line.
        hunks = parse_v4a("-a\n\n+b\n")
        assert hunks[0].before == ("a", "")
        assert hunks[0].after == ("", "b")

    def test_an_unprefixed_line_is_refused_rather_than_guessed_at(self):
        with pytest.raises(ToolError) as e:
            parse_v4a("-a\nnot prefixed\n+b\n")
        assert "must begin with a space" in str(e.value)

    def test_the_envelope_is_stripped_rather_than_refused(self):
        # Two canonical spellings of this format exist and models emit both.
        # The envelope is redundant beside `path` and `type`, not wrong.
        hunks = parse_v4a(
            "*** Begin Patch\n*** Update File: a.rb\n-a\n+b\n*** End Patch\n",
            "a.rb",
        )
        assert len(hunks) == 1
        assert (hunks[0].before, hunks[0].after) == (("a",), ("b",))

    def test_a_trailing_end_patch_alone_is_stripped(self):
        # The measured shape: the model omits `*** Begin Patch` because the
        # description named it, and still closes with the other half.
        hunks = parse_v4a("-a\n+b\n*** End Patch\n", "a.rb")
        assert (hunks[0].before, hunks[0].after) == (("a",), ("b",))

    def test_a_bare_star_line_is_stripped(self):
        # Models truncate the named markers to their punctuation. Three of ten
        # refusals on the first run after the envelope was tolerated were a
        # lone `***` closing the patch, all on one hunk retried verbatim.
        hunks = parse_v4a("-a\n+b\n***\n", "a.rb")
        assert (hunks[0].before, hunks[0].after) == (("a",), ("b",))

    def test_an_end_of_file_marker_is_stripped(self):
        hunks = parse_v4a("-a\n+b\n*** End of File\n", "a.rb")
        assert (hunks[0].before, hunks[0].after) == (("a",), ("b",))

    def test_an_envelope_naming_another_file_is_refused(self):
        # The one envelope line that can disagree with the arguments. Guessing
        # which half is meant is the wrong-but-plausible write this tool exists
        # to prevent.
        with pytest.raises(ToolError) as e:
            parse_v4a("*** Update File: other.rb\n-a\n+b\n", "a.rb")
        assert "other.rb" in str(e.value) and "a.rb" in str(e.value)

    def test_a_non_envelope_triple_star_line_is_still_refused(self):
        with pytest.raises(ToolError) as e:
            parse_v4a("*** Frobnicate\n-a\n+b\n", "a.rb")
        assert "not V4A" in str(e.value)

    def test_a_context_line_beginning_with_stars_is_content(self):
        # A real `***` line in a file arrives with its context space, so the
        # envelope check must not reach it.
        hunks = parse_v4a(" *** stars\n-a\n+b\n", "a.rb")
        assert hunks[0].before == ("*** stars", "a")

    def test_a_hunk_that_asks_for_no_change_is_refused(self):
        with pytest.raises(ToolError) as e:
            parse_v4a(" a\n b\n")
        assert "no change" in str(e.value)

    def test_a_bare_header_used_as_an_elision_is_named_as_the_cause(self):
        """The shape behind every no-op refusal on record.

        A scoped hunk of pure context, then a bare `@@` meaning "skip ahead",
        then the real change: two hunks to the format, one to the model. The
        reference parser refuses it too. Told only that "a hunk" asked for no
        change, a model re-sent the identical patch three times; the refusal
        has to say which hunk and that the `@@` split it.
        """
        with pytest.raises(ToolError) as e:
            parse_v4a(
                "@@ describe '.load_item' do\n"
                "     it 'unmarshals' do\n"
                "       session = {}\n"
                "@@\n"
                "     end\n"
                "+\n"
                "+    it 'loads' do\n"
                "+    end\n"
            )
        said = str(e.value)
        assert "hunk 1 of 2" in said
        assert "describe '.load_item' do" in said
        assert "starts a new hunk" in said
        assert "2 line(s)" in said

    def test_a_lone_hunk_is_still_told_what_to_add(self):
        # The single-hunk wording is unchanged in substance: no `@@` split it,
        # so naming one would send the model looking for a header it did not write.
        with pytest.raises(ToolError) as e:
            parse_v4a(" a\n b\n")
        assert "the hunk is context only" in str(e.value)
        assert "starts a new hunk" not in str(e.value)

    def test_consecutive_headers_nest(self):
        text = "class A\n  def go\n    save\n  end\nend\nclass B\n  def go\n    save\n  end\nend\n"
        out = apply_v4a(
            text, parse_v4a("@@ class B\n@@ def go\n-    save\n+    save!\n")
        )
        assert out.count("save!") == 1
        assert out.index("save!") > out.index("class B")


class TestTheGuardsAreShared:
    # The safety story guards the *path*, and the payload's shape does not
    # reach it. Asserted rather than assumed, because a second write tool is
    # exactly where a second, laxer resolution would go unnoticed.
    def test_scope_is_enforced(self, editor):
        with pytest.raises(ToolError) as e:
            editor.apply_patch("other/x.rb", "update_file", "-a\n+b\n")
        assert "not in this stage's scope" in str(e.value)

    def test_no_direct_edit_is_enforced(self, editor):
        with pytest.raises(ToolError) as e:
            editor.apply_patch("bin/gen.rb", "update_file", "-# generated\n+# no\n")
        assert e.value.kind == "no direct edit"

    def test_plan_documents_are_protected(self, editor):
        editor.protected = lambda rel: rel.startswith("spec/")
        with pytest.raises(ToolError) as e:
            editor.apply_patch("spec/a_spec.rb", "update_file", "-x\n+y\n")
        assert "plans from" in str(e.value)

    def test_a_path_outside_the_repository_is_refused(self, editor):
        with pytest.raises(ToolError) as e:
            editor.apply_patch("../escape.rb", "update_file", "-a\n+b\n")
        assert "outside the repository" in str(e.value)


class TestOperations:
    def test_create_file_takes_added_lines_only(self, editor):
        editor.apply_patch("spec/new_spec.rb", "create_file", "+one\n+two\n")
        assert read(editor, "spec/new_spec.rb") == "one\ntwo\n"

    def test_create_file_refuses_a_hunk_with_context(self, editor):
        with pytest.raises(ToolError) as e:
            editor.apply_patch("spec/new_spec.rb", "create_file", " one\n+two\n")
        assert "may only add lines" in str(e.value)

    def test_delete_file_goes_through_the_existing_tool(self, editor):
        editor.apply_patch("spec/a_spec.rb", "delete_file", "")
        assert not (editor.repo / "spec/a_spec.rb").exists()

    def test_an_unknown_operation_names_the_three(self, editor):
        with pytest.raises(ToolError) as e:
            editor.apply_patch("spec/a_spec.rb", "patch_file", "-a\n+b\n")
        assert "is not an operation" in str(e.value)


class TestTheEcho:
    """What a successful write hands back.

    A tool result of "applied 1 edit(s)" leaves the model holding a prediction
    of what the file now says. This codebase already knows what that costs on
    the other side of the same seam — a check that rewrites files after the
    model stops leaves its context stale, and the fix was to hand back the diff
    and attribute it. This is the same fact one step earlier, and it is the one
    change nobody was telling the model about: its own.
    """

    def test_a_write_answers_with_the_bytes_it_produced(self, tmp_path):
        ed = _repo_with(tmp_path, "app/a.rb", "one\ntwo\nthree\n")
        out = ed.apply_patch("app/a.rb", "update_file", "-two\n+TWO\n")
        assert "It now reads:" in out
        assert "TWO" in out

    def test_the_echo_is_numbered_the_way_read_file_numbers(self, tmp_path):
        from code_gantry.repotools import number_lines

        ed = _repo_with(tmp_path, "app/a.rb", "one\ntwo\nthree\n")
        out = ed.apply_patch("app/a.rb", "update_file", "-two\n+TWO\n")
        # Quotable straight back into the next `old_string` without a
        # `read_file` in between, which is the whole point.
        assert number_lines(["one", "TWO", "three"], 1) in out

    def test_edit_answers_the_same_way(self, tmp_path):
        # Both writing tools or neither. A model choosing between them should
        # not also be choosing between two success contracts.
        ed = _repo_with(tmp_path, "app/a.rb", "one\ntwo\nthree\n")
        out = ed.edit("app/a.rb", [Edit(old_string="two", new_string="TWO")])
        assert "It now reads:" in out
        assert "TWO" in out

    def test_the_echo_shows_where_the_edit_actually_landed(self, tmp_path):
        # Regions come from diffing before against after, not from what the
        # caller asked for — the two differ exactly when it matters.
        ed = _repo_with(tmp_path, "app/a.rb", "a\nb\nc\nd\ne\nf\ng\nh\ni\nj\nk\n")
        from code_gantry.repotools import number_lines

        out = ed.edit("app/a.rb", [Edit(old_string="j", new_string="J")])
        assert number_lines(["J"], 10) in out
        assert number_lines(["a"], 1) not in out

    def test_a_change_too_large_to_quote_says_so_instead(self, tmp_path):
        ed = _repo_with(tmp_path, "app/a.rb", "x\n" * 200)
        out = ed.edit(
            "app/a.rb", [Edit(old_string="x\n" * 200, new_string="y\n" * 200)]
        )
        assert "too many to quote back" in out
        assert "read_file" in out

    def test_a_deletion_still_shows_the_seam(self, tmp_path):
        # A deletion has a zero-width span in the after-text, and a window of
        # nothing would render as "no change" — the one outcome that must not
        # look like success with an empty answer.
        ed = _repo_with(tmp_path, "app/a.rb", "one\ntwo\nthree\n")
        out = ed.apply_patch("app/a.rb", "update_file", "-two\n")
        assert "It now reads:" in out
        assert "one" in out and "three" in out

    def test_no_window_when_nothing_changed(self):
        assert changed_windows("a\nb\n", "a\nb\n") == ""


def _repo_with(tmp_path, rel, content):
    repo = tmp_path / "r"
    path = repo / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    for args in (
        ["git", "init", "-q"],
        ["git", "config", "user.email", "t@example.com"],
        ["git", "config", "user.name", "T"],
        ["git", "config", "commit.gpgsign", "false"],
        ["git", "add", "-A"],
        ["git", "commit", "-q", "-m", "first"],
    ):
        subprocess.run(args, cwd=repo, check=True)
    return FileEditor(repo=repo, edit_files=["**"])
